### ISSUE TITLE
真机预览报错Json无法处理

### ISSUE THREAD

**Issue by longerking** [Hansuku/blazeface-miniprogram#2]
你好，使用真机调试是，遇到一下报错：
请问你有遇到过吗？十分期待你的帮助!

![image](https://user-images.githubusercontent.com/37200736/142998407-f096abc3-d296-4c6e-9437-830ee383b392.png)

**Comment by Hansuku** [comment]
看一下报错点吧 这样截图看不到什么信息

**Comment by longerking** [comment]
开发时候可以正常加载模型且一切工作正常，但是真机调试预览时候就出现了这个错，毫无头绪。报错点是编译后的，无从着手。

**Comment by longerking** [comment]
> 看一下报错点吧 这样截图看不到什么信息


开发时候可以正常加载模型且一切工作正常，但是真机调试预览时候就出现了这个错，毫无头绪。报错点是编译后的，无从着手。
