### ISSUE TITLE
调试和发布，无法加载模型

### ISSUE THREAD

**Issue by longerking** [Hansuku/blazeface-miniprogram#3]
你好，基于你的案例，我更换了自己oss上的ModelUrl， model.json和.bin文件。开发测试良好。
且已经加入白名单
但是开启真机调试时候，或者推体验版后无法正确请求.bin文件呢。请问是什么原因呢？

类似这样的描述：
https://developers.weixin.qq.com/community/develop/doc/000ce68f188ce0001b2d5ad095bc00

**Comment by Hansuku** [comment]
> 你好，基于你的案例，我更换了自己oss上的ModelUrl， model.json和.bin文件。开发测试良好。 且已经加入白名单 但是开启真机调试时候，或者推体验版后无法正确请求.bin文件呢。请问是什么原因呢？
> 
> 类似这样的描述： https://developers.weixin.qq.com/community/develop/doc/000ce68f188ce0001b2d5ad095bc00

看起来应该是微信那边的改动导致的 你可以试一下往 oss 里随便放一个 bin 文件然后去请求下看看
